import type { AncientPlace } from "./places";

// Generated from archaia_ellada_hierarchy (1).csv. Source IDs are offset by 100000
// to avoid collisions with places created in the browser.
export const catalogPlaces: AncientPlace[] = [
  {
    "id": 100001,
    "nomosId": "kavala",
    "name": "Κορυφη Αυγο Παγγαιο",
    "location": "Παγγαίο, Καβάλα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.90735513121323",
    "longitude": "24.10790016103253",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100002,
    "nomosId": "thessaloniki",
    "name": "Οκτάγωνο του Ανακτορικού Συγκροτήματος Γαλερίου",
    "location": "Θεσσαλονίκη / κέντρο, Θεσσαλονίκη",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.630432",
    "longitude": "22.949418",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100003,
    "nomosId": "korinthia",
    "name": "Ηραίο Περαχώρας",
    "location": "Περαχώρα / Ηραίο, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.02809999999999",
    "longitude": "22.8528",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100004,
    "nomosId": "fokida",
    "name": "Αρχαιολογικός χώρος Δελφών",
    "location": "Δελφοί, Φωκίδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.48264",
    "longitude": "22.50107999999999",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100005,
    "nomosId": "attiki-athina",
    "name": "Πιθανή θέση της Ποικίλης Στοάς",
    "location": "Αρχαία Αγορά / Αθήνα, Κεντρικός Τομέας Αθηνών",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.97616",
    "longitude": "23.7224",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100006,
    "nomosId": "korinthia",
    "name": "Αρχαίος Φενεός και οι «καταβόθρες του Ηρακλή»",
    "location": "Φενεός, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.9117",
    "longitude": "22.307",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100007,
    "nomosId": "attiki-dytiki",
    "name": "Μεγάλα Προπύλαια Ελευσίνας",
    "location": "Ελευσίνα, Δυτική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.0411",
    "longitude": "23.538",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100008,
    "nomosId": "attiki-peiraias",
    "name": "[χωρίς όνομα]",
    "location": "Τροιζηνία / Μέθανα, Νήσων",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.5958432",
    "longitude": "23.0768899",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100009,
    "nomosId": "attiki-athina",
    "name": "Θέατρο Διονύσου, Νότια Κλιτύς Ακρόπολης",
    "location": "Ακρόπολη / Νότια Κλιτύς, Κεντρικός Τομέας Αθηνών",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.9703",
    "longitude": "23.7278",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100010,
    "nomosId": "attiki-athina",
    "name": "Στοά Ευμένους",
    "location": "Ακρόπολη / Νότια Κλιτύς, Κεντρικός Τομέας Αθηνών",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.9705",
    "longitude": "23.726",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100011,
    "nomosId": "attiki-athina",
    "name": "Κλεψύδρα και μυκηναϊκή κρυφή πρόσβαση της βόρειας κλιτύος",
    "location": "Ακρόπολη / Βόρεια Κλιτύς, Κεντρικός Τομέας Αθηνών",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.97207",
    "longitude": "23.72512",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100012,
    "nomosId": "messinia",
    "name": "Ασκληπιείο Αρχαίας Μεσσήνης",
    "location": "Αρχαία Μεσσήνη, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.17554",
    "longitude": "21.92064",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100013,
    "nomosId": "attiki-athina",
    "name": "Ιερό/Ασκληπιείο κάτω από την Ακρόπολη",
    "location": "Ακρόπολη / Νότια Κλιτύς, Κεντρικός Τομέας Αθηνών",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.9708",
    "longitude": "23.7268",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100014,
    "nomosId": "voiotia",
    "name": "Ιερό Αρτέμιδος Αυλιδείας",
    "location": "Αυλίδα, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.4335",
    "longitude": "23.5925",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100015,
    "nomosId": "attiki-dytiki",
    "name": "Αρχαία γέφυρα/διάβαση του Κηφισού στην Ιερά Οδό",
    "location": "Ιερά Οδός / Ελευσίνα, Δυτική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.04945",
    "longitude": "23.55515",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100016,
    "nomosId": "attiki-dytiki",
    "name": "Αρχαιολογικός χώρος Ελευσίνας",
    "location": "Ελευσίνα, Δυτική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.0411",
    "longitude": "23.538",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100017,
    "nomosId": "fokida",
    "name": "Αρχαίο θέατρο Δελφών",
    "location": "Δελφοί, Φωκίδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.48248",
    "longitude": "22.50058",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100018,
    "nomosId": "pella",
    "name": "Αρχαιολογικός χώρος Πέλλας",
    "location": "Πέλλα, Πέλλα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.754",
    "longitude": "22.518",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100019,
    "nomosId": "kilkis",
    "name": "Αρχαίος Ευρωπός",
    "location": "Ευρωπός, Κιλκίς",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.8863",
    "longitude": "22.554",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100020,
    "nomosId": "serres",
    "name": "Αρχαία Άργιλος",
    "location": "Άργιλος / Αμφίπολη, Σέρρες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.7801",
    "longitude": "23.8168",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100021,
    "nomosId": "attiki-athina",
    "name": "Κεραμεικός, νεκροταφείο",
    "location": "Κεραμεικός, Κεντρικός Τομέας Αθηνών",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.9781",
    "longitude": "23.71879999999999",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100022,
    "nomosId": "ileia",
    "name": "Ηραίο Ολυμπίας",
    "location": "Ολυμπία, Ηλεία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.63886",
    "longitude": "21.62998",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100023,
    "nomosId": "korinthia",
    "name": "Ναός Απόλλωνος στην Αρχαία Κόρινθο",
    "location": "Αρχαία Κόρινθος, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.90597",
    "longitude": "22.87904",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100024,
    "nomosId": "messinia",
    "name": "Παλαίστρα και λουτρά Αρχαίας Μεσσήνης",
    "location": "Αρχαία Μεσσήνη, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.1779",
    "longitude": "21.9195",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100025,
    "nomosId": "korinthia",
    "name": "Ρωμαϊκά λουτρά / βαλανεία στον αρχαιολογικό χώρο",
    "location": "Αρχαία Κόρινθος, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.9064",
    "longitude": "22.88059999999999",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100026,
    "nomosId": "voiotia",
    "name": "[χωρίς όνομα]",
    "location": "Λιβαδειά / Τροφώνιο, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.4312176",
    "longitude": "22.87347399999999",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100027,
    "nomosId": "serres",
    "name": "[χωρίς όνομα]",
    "location": "Αμφίπολη, Σέρρες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.8251772",
    "longitude": "23.8488304",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100028,
    "nomosId": "serres",
    "name": "[χωρίς όνομα]",
    "location": "Αμφίπολη, Σέρρες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.8393828",
    "longitude": "23.8628197",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100029,
    "nomosId": "serres",
    "name": "[χωρίς όνομα]",
    "location": "Αμφίπολη / Άργιλος, Σέρρες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.803074",
    "longitude": "23.8425408",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100030,
    "nomosId": "arkadia",
    "name": "Βωμός της Δέσποινας στο ιερό της Αρκαδικής θεότητας",
    "location": "Λυκόσουρα, Αρκαδία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.5117",
    "longitude": "22.084",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100031,
    "nomosId": "arkadia",
    "name": "Ναός Επικουρίου Απόλλωνος",
    "location": "Βάσσες / Φιγαλεία, Αρκαδία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.4299261",
    "longitude": "21.9000103",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100032,
    "nomosId": "arkadia",
    "name": "Λύκαιο Όρος, ιερό Δία, στάδιο/ιππόδρομο",
    "location": "Λύκαιο Όρος, Αρκαδία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.4484",
    "longitude": "21.9954",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100033,
    "nomosId": "voiotia",
    "name": "Ιερό των Μουσών",
    "location": "Ελικώνας / Κοιλάδα Μουσών, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.3208",
    "longitude": "23.0587",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100034,
    "nomosId": "serres",
    "name": "Τάφος Βρασίδα",
    "location": "Αμφίπολη, Σέρρες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.8252",
    "longitude": "23.84886",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100035,
    "nomosId": "attiki-athina",
    "name": "Ιερό της Αφροδίτης",
    "location": "Ιερά Οδός / Δαφνί, Δυτικός Τομέας Αθηνών",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.01278",
    "longitude": "23.61598",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100036,
    "nomosId": "imathia",
    "name": "Μακεδονικός Τάφος των Ανθεμίων",
    "location": "Μίεζα / Νάουσα, Ημαθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.65462",
    "longitude": "22.13934",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100037,
    "nomosId": "attiki-dytiki",
    "name": "[χωρίς όνομα]",
    "location": "Ελευθερές / Βίλια, Δυτική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.16357199999999",
    "longitude": "23.424708",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100038,
    "nomosId": "voiotia",
    "name": "Αρχαία Θήβα/ Αρχαίο νεκροταφείο/τύμβος",
    "location": "Θήβα, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.32083",
    "longitude": "23.31778",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100039,
    "nomosId": "preveza",
    "name": "Αρχαιολογικό Μουσείο Νικόπολης",
    "location": "Νικόπολη, Πρέβεζα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.027981",
    "longitude": "20.735609",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100040,
    "nomosId": "attiki-anatoliki",
    "name": "Αμφιάρειο Ωρωπού",
    "location": "Ωρωπός / Αμφιάρειο, Ανατολική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.290736",
    "longitude": "23.844791",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100041,
    "nomosId": "arkadia",
    "name": "Αρχαία Τραπεζούντα Αρκαδίας",
    "location": "Τραπεζούντα Αρκαδίας, Αρκαδία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.44861",
    "longitude": "22.0725",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100042,
    "nomosId": "voiotia",
    "name": "Κοιλάδα των Μουσών",
    "location": "Ελικώνας / Κοιλάδα Μουσών, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.316008",
    "longitude": "23.06004",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100043,
    "nomosId": "argolida",
    "name": "Αρχαίοτερο γεφύρι στο Αρκαδικό",
    "location": "Αρκαδικό / Μυκηναϊκός δρόμος, Αργολίδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.59378",
    "longitude": "22.93756999999999",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100044,
    "nomosId": "korinthia",
    "name": "Οι καταβόθρες του Ηρακλή στους αρχαίους Φενεούς",
    "location": "Φενεός, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.85789275562806",
    "longitude": "22.28335667907987",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100045,
    "nomosId": "attiki-anatoliki",
    "name": "[χωρίς όνομα]",
    "location": "Βόρεια Αττική / άγνωστο pin, Ανατολική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.0707654",
    "longitude": "23.8772214",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100046,
    "nomosId": "arkadia",
    "name": "Βωμός του Δία",
    "location": "Λύκαιο Όρος, Αρκαδία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.446278",
    "longitude": "21.9895",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100047,
    "nomosId": "attiki-athina",
    "name": "Αρχαία Αγορά της Αθήνας",
    "location": "Αρχαία Αγορά / Αθήνα, Κεντρικός Τομέας Αθηνών",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.9746",
    "longitude": "23.7217",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100048,
    "nomosId": "lasithi",
    "name": "Δικταίο Άντρο",
    "location": "Δικταίο Άντρο / Οροπέδιο Λασιθίου, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.162861",
    "longitude": "25.445061",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100049,
    "nomosId": "rethymno",
    "name": "Ιδαίο Άντρο",
    "location": "Ιδαίο Άντρο / Ψηλορείτης, Ρέθυμνο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.208361",
    "longitude": "24.828944",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100050,
    "nomosId": "imathia",
    "name": "Νυμφαίο Μίεζας",
    "location": "Μίεζα / Νάουσα, Ημαθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.629793",
    "longitude": "22.085723",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100051,
    "nomosId": "attiki-dytiki",
    "name": "Ρωμαϊκή Γέφυρα στον Ελευσινιακό Κηφισό",
    "location": "Ιερά Οδός / Ελευσίνα, Δυτική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.04718",
    "longitude": "23.55108",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100052,
    "nomosId": "voiotia",
    "name": "Μαντείο Τροφωνίου",
    "location": "Λιβαδειά / Τροφώνιο, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.431194",
    "longitude": "22.875",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100053,
    "nomosId": "voiotia",
    "name": "Μυκηναϊκοί θαλαμωτοί τάφοι",
    "location": "Αυλίδα, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.4131",
    "longitude": "23.6728",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100054,
    "nomosId": "pella",
    "name": "Αρχαιολογικός χώρος Πέλλας",
    "location": "Πέλλα, Πέλλα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.76",
    "longitude": "22.519167",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100055,
    "nomosId": "lasithi",
    "name": "Ανάκτορο Μαλίων",
    "location": "Μάλια, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.293455",
    "longitude": "25.492197",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100056,
    "nomosId": "samos",
    "name": "Ευπαλίνειο Όρυγμα, Πυθαγόρειο",
    "location": "Πυθαγόρειο / Σάμος, Σάμος",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.694",
    "longitude": "26.93",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100057,
    "nomosId": "messinia",
    "name": "Αρχαία Μεσσήνη",
    "location": "Αρχαία Μεσσήνη, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.175",
    "longitude": "21.92",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100058,
    "nomosId": "preveza",
    "name": "Αρχαία Νικόπολη",
    "location": "Νικόπολη, Πρέβεζα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.00933",
    "longitude": "20.73353",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100059,
    "nomosId": "korinthia",
    "name": "Αρχαίος λιμένας Κεγχρεών",
    "location": "Κεγχρεές, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.8824",
    "longitude": "22.9925",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100060,
    "nomosId": "arkadia",
    "name": "Αρχαίος Ορχομενός Αρκαδίας",
    "location": "Ορχομενός Αρκαδίας, Αρκαδία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.7247",
    "longitude": "22.3154",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100061,
    "nomosId": "fthiotida",
    "name": "Θερμοπύλες, Μνημείο Λεωνίδα",
    "location": "Θερμοπύλες, Φθιώτιδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.796781",
    "longitude": "22.536561",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100062,
    "nomosId": "voiotia",
    "name": "Τρόπαιο Επαμεινώνδα",
    "location": "Λεύκτρα, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.2647",
    "longitude": "23.1743",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100063,
    "nomosId": "attiki-anatoliki",
    "name": "Ναός Ποσειδώνα",
    "location": "Σούνιο, Ανατολική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.65025",
    "longitude": "24.024556",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100064,
    "nomosId": "messinia",
    "name": "Αρχαιολογικό Μουσείο Πύλου",
    "location": "Πύλος, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.912222",
    "longitude": "21.691944",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100065,
    "nomosId": "mikra-asia-tourkia",
    "name": "Ναός Απόλλωνα, Δίδυμα",
    "location": "Δίδυμα / Ιωνία, Μικρά Ασία / Τουρκία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.385",
    "longitude": "27.256389",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100066,
    "nomosId": "attiki-athina",
    "name": "Αδριάνειο Υδραγωγείο",
    "location": "Αδριάνειο Υδραγωγείο, Βόρειος Τομέας Αθηνών",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.033596",
    "longitude": "23.773283",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100067,
    "nomosId": "pieria",
    "name": "Αρχαιολογικο Πάρκο Δίον",
    "location": "Δίον, Πιερία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.175556",
    "longitude": "22.494444",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100068,
    "nomosId": "messinia",
    "name": "Βασιλικός μυκηναϊκός θολωτός τάφος",
    "location": "Πύλος / Ανάκτορο Νέστορα, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.007301",
    "longitude": "21.666804",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100069,
    "nomosId": "voiotia",
    "name": "Αρχαιολογικό Μουσείο Θηβών",
    "location": "Θήβα, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.32361",
    "longitude": "23.31778",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100070,
    "nomosId": "thessaloniki",
    "name": "Κρύπτη Αγίου Δημητρίου",
    "location": "Θεσσαλονίκη / κέντρο, Θεσσαλονίκη",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.63889",
    "longitude": "22.94778",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100071,
    "nomosId": "thessaloniki",
    "name": "Μακεδονικός Τάφος Λαγκαδά",
    "location": "Λαγκαδάς, Θεσσαλονίκη",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.71499",
    "longitude": "22.960782",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100072,
    "nomosId": "chalkidiki",
    "name": "[χωρίς όνομα]",
    "location": "Χαλκιδική / άγνωστο pin, Χαλκιδική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.3733567",
    "longitude": "23.1680397",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100073,
    "nomosId": "attiki-peiraias",
    "name": "Σπήλαιο Ευριπίδη",
    "location": "Σαλαμίνα, Νήσων",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.8823",
    "longitude": "23.4523",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100074,
    "nomosId": "attiki-anatoliki",
    "name": "Ιερό Αρτέμιδος Βραυρωνίας",
    "location": "Βραυρώνα, Ανατολική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.92611",
    "longitude": "23.99361",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100075,
    "nomosId": "voiotia",
    "name": "Πύργος Αλιάρτου/Μουλκίου",
    "location": "Αλίαρτος, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.36778",
    "longitude": "23.11999999999999",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100076,
    "nomosId": "attiki-athina",
    "name": "Ακαδημία Πλάτωνος",
    "location": "Ακαδημία Πλάτωνος, Κεντρικός Τομέας Αθηνών",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.99140937241722",
    "longitude": "23.70826415858035",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100077,
    "nomosId": "voiotia",
    "name": "Ιερό Καβείρων / θέατρο Καβείριων μυστηρίων",
    "location": "Θήβα / Καβείριο, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.318333",
    "longitude": "23.255278",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100078,
    "nomosId": "korinthia",
    "name": "Υδραυλικό σύστημα Κρήνης",
    "location": "Περαχώρα / Ηραίο, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.0299",
    "longitude": "22.8582",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100079,
    "nomosId": "korinthia",
    "name": "Βραχοκομμένες δεξαμενές Ηραίου Περαχώρας",
    "location": "Περαχώρα / Ηραίο, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.0306",
    "longitude": "22.8604",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100080,
    "nomosId": "arta",
    "name": "Αρχαιολογικός Χώρος Όρραον/ Αρχαία Ακρόπολη Μολοσσών",
    "location": "Όρραον, Άρτα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.271293",
    "longitude": "20.925136",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100081,
    "nomosId": "attiki-anatoliki",
    "name": "Ιερό Νέμεσης",
    "location": "Ραμνούντας, Ανατολική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.22333",
    "longitude": "24.02722",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100082,
    "nomosId": "voiotia",
    "name": "Μυκηναϊκή ακρόπολη",
    "location": "Κωπαΐδα / Γλα, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.48333",
    "longitude": "23.18222",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100083,
    "nomosId": "kyklades",
    "name": "Αρχαία Καρθαία",
    "location": "Κέα / Καρθαία, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.5615",
    "longitude": "24.33072",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100084,
    "nomosId": "lesvos",
    "name": "Αρχαίος Οίκισμος Πολιόχνη",
    "location": "Πολιόχνη, Λήμνος",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.85417",
    "longitude": "25.34361",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100085,
    "nomosId": "karditsa",
    "name": "Αρχαία πόλη/οχύρωση Στρογγυλοβούνι",
    "location": "Στρογγυλοβούνι, Καρδίτσα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.50526",
    "longitude": "22.0861",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100086,
    "nomosId": "lasithi",
    "name": "Αρχαία δωρική πόλη Λατώ",
    "location": "Λατώ, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.17778",
    "longitude": "25.65361",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100087,
    "nomosId": "lasithi",
    "name": "Αρχαϊκή πόλη Δρήρος",
    "location": "Δρήρος, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.25667",
    "longitude": "25.62833",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100088,
    "nomosId": "rethymno",
    "name": "Αρχαία Ελεύθερνα",
    "location": "Ελεύθερνα, Ρέθυμνο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.3207",
    "longitude": "24.66431",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100089,
    "nomosId": "lasithi",
    "name": "Αρχαϊκή πόλη Αζοριάς",
    "location": "Αζοριάς / Καβούσι, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.11030492554622",
    "longitude": "25.85824420131565",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100090,
    "nomosId": "lasithi",
    "name": "Μινωική πόλη Γουρνιά",
    "location": "Γουρνιά, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.10959292896278",
    "longitude": "25.7926706511745",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100091,
    "nomosId": "lasithi",
    "name": "Ορεινός μινωικός οικισμός Καρφί",
    "location": "Καρφί / Οροπέδιο Λασιθίου, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.20185560081324",
    "longitude": "25.48760726574691",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100092,
    "nomosId": "lakonia",
    "name": "Παυλοπέτρι",
    "location": "Παυλοπέτρι / Ελαφόνησος, Λακωνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.5",
    "longitude": "22.99",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100093,
    "nomosId": "preveza",
    "name": "Αρχαία Κασσώπη",
    "location": "Κασσώπη, Πρέβεζα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.1455343",
    "longitude": "20.67739",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100094,
    "nomosId": "preveza",
    "name": "Νεκρομαντείο Αχέροντα",
    "location": "Αχέροντας / Νεκρομαντείο, Πρέβεζα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.2369",
    "longitude": "20.535",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100095,
    "nomosId": "thesprotia",
    "name": "Αρχαία Γίτανα",
    "location": "Γίτανα, Θεσπρωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.57109938144574",
    "longitude": "20.26164731851269",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100096,
    "nomosId": "thesprotia",
    "name": "Αρχαία πόλη της Eλέας",
    "location": "Ελέα, Θεσπρωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.44",
    "longitude": "20.5505556",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100097,
    "nomosId": "ioannina",
    "name": "Μαντείο της Δωδώνης",
    "location": "Δωδώνη, Ιωάννινα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.54639",
    "longitude": "20.78778",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100098,
    "nomosId": "magnisia",
    "name": "Αρχαίος Οίκισμος Σέσκλο",
    "location": "Σέσκλο, Μαγνησία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.3555556",
    "longitude": "22.8411111",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100099,
    "nomosId": "magnisia",
    "name": "Μυκηναϊκός χώρος Διμήνι",
    "location": "Διμήνι, Μαγνησία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.3616667",
    "longitude": "22.8930556",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100100,
    "nomosId": "attiki-dytiki",
    "name": "Αρχαίο Φρούριο Αιγοσθένων",
    "location": "Αιγόσθενα / Πόρτο Γερμενό, Δυτική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.1475",
    "longitude": "23.22861",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100101,
    "nomosId": "chania",
    "name": "Αρχαία Άπτερα",
    "location": "Άπτερα, Χανιά",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.4629",
    "longitude": "24.142",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100102,
    "nomosId": "attiki-dytiki",
    "name": "Οχυρό Ελευθερών / Γυφτόκαστρο",
    "location": "Ελευθερές / Γυφτόκαστρο, Δυτική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.17944",
    "longitude": "23.37583",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100103,
    "nomosId": "attiki-dytiki",
    "name": "Φρούριο Φυλής",
    "location": "Φυλή, Δυτική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.14",
    "longitude": "23.637",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100104,
    "nomosId": "korinthia",
    "name": "Αρχαία Στύμφαλος",
    "location": "Στύμφαλος, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.85932",
    "longitude": "22.45931",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100105,
    "nomosId": "argolida",
    "name": "Μυκηναϊκή Ακρόπολη Μιδέας",
    "location": "Μιδέα, Αργολίδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.64971999999999",
    "longitude": "22.84139",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100106,
    "nomosId": "argolida",
    "name": "Αρχαία Ασίνη / Καστράκι Τολού",
    "location": "Ασίνη / Τολό, Αργολίδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.52659",
    "longitude": "22.87403",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100107,
    "nomosId": "argolida",
    "name": "Λέρνα / Οικία των Κεράμων",
    "location": "Λέρνα, Αργολίδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.55118385448146",
    "longitude": "22.71827860673239",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100108,
    "nomosId": "aitoloakarnania",
    "name": "Αρχαία Πλευρώνα",
    "location": "Πλευρώνα, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.414413",
    "longitude": "21.409739",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100109,
    "nomosId": "aitoloakarnania",
    "name": "Οινιάδες / Αρχαία Νεώρια",
    "location": "Οινιάδες, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.4117",
    "longitude": "21.195",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100110,
    "nomosId": "irakleio",
    "name": "Φαιστός",
    "location": "Φαιστός, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.05139",
    "longitude": "24.81361",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100111,
    "nomosId": "irakleio",
    "name": "Μινωική Έπαυλη Αγίας Τριάδας",
    "location": "Αγία Τριάδα / Φαιστός, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.05889",
    "longitude": "24.7925",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100112,
    "nomosId": "irakleio",
    "name": "Γόρτυνα / Γόρτυς",
    "location": "Γόρτυνα, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.063079",
    "longitude": "24.946866",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100113,
    "nomosId": "lasithi",
    "name": "Ανάκτορο Ζάκρου",
    "location": "Ζάκρος, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.09806",
    "longitude": "26.26139",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100114,
    "nomosId": "kyklades",
    "name": "Αρχαία Θήρα",
    "location": "Θήρα / Αρχαία Θήρα, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.364586",
    "longitude": "25.477939",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100115,
    "nomosId": "kyklades",
    "name": "Προϊστορική πόλη Ακρωτήρι Θήρας",
    "location": "Θήρα / Ακρωτήρι, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.35138999999999",
    "longitude": "25.40361",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100116,
    "nomosId": "chania",
    "name": "Αρχαία Κίσσαμος",
    "location": "Κίσσαμος, Χανιά",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.457977",
    "longitude": "23.655626",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100117,
    "nomosId": "lesvos",
    "name": "Ηφαιστία",
    "location": "Ηφαιστία, Λήμνος",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.9645",
    "longitude": "25.3182",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100118,
    "nomosId": "lasithi",
    "name": "Μινωική πόλη Παλαίκαστρο",
    "location": "Παλαίκαστρο, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.195306",
    "longitude": "26.275583",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100119,
    "nomosId": "lasithi",
    "name": "Ερημούπολη",
    "location": "Ίτανος / Ερημούπολη, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.26476167131896",
    "longitude": "26.26284856463726",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100120,
    "nomosId": "lasithi",
    "name": "Μινωικός Οικισμός Μόχλου",
    "location": "Μόχλος, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.18658979763335",
    "longitude": "25.90648522953876",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100121,
    "nomosId": "chania",
    "name": "Αρχαία Φαλάσαρνας",
    "location": "Φαλάσαρνα, Χανιά",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.51078341116694",
    "longitude": "23.5693783169439",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100122,
    "nomosId": "irakleio",
    "name": "Μινωικός χώρος Τυλίσου",
    "location": "Τύλισος, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.29868924241772",
    "longitude": "25.02055037620885",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100123,
    "nomosId": "irakleio",
    "name": "Οικία των Κρίνων",
    "location": "Αμνισός / Κνωσός, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.3308333",
    "longitude": "25.2061111",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100124,
    "nomosId": "irakleio",
    "name": "Μινωική έπαυλη Βαθυπέτρου",
    "location": "Βαθύπετρο / Αρχάνες, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.20554012350704",
    "longitude": "25.15850339849739",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100125,
    "nomosId": "irakleio",
    "name": "[χωρίς όνομα]",
    "location": "Ηράκλειο / άγνωστο pin, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.2554291",
    "longitude": "25.1445758",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100126,
    "nomosId": "irakleio",
    "name": "Κομμός / Μινωικό λιμάνι Κομμού",
    "location": "Κομμός, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.0133333",
    "longitude": "24.7608333",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100127,
    "nomosId": "lasithi",
    "name": "Πραισός / αρχαία πόλη των Ετεοκρητών",
    "location": "Πραισός, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.12301145636765",
    "longitude": "26.09079981691396",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100128,
    "nomosId": "preveza",
    "name": "Πανδοσία Ηπείρου",
    "location": "Αχέροντας / Πανδοσία, Πρέβεζα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.2525",
    "longitude": "20.5744444",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100129,
    "nomosId": "preveza",
    "name": "Κίχυρος / Εφύρα Θεσπρωτίας",
    "location": "Αχέροντας / Εφύρα-Κίχυρος, Πρέβεζα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.242391",
    "longitude": "20.53143",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100130,
    "nomosId": "fthiotida",
    "name": "Ακρόπολη Πρόερνας",
    "location": "Πρόερνα / Δομοκός, Φθιώτιδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.24267648873428",
    "longitude": "22.2807694306354",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100131,
    "nomosId": "fthiotida",
    "name": "Αρχαία Μελιταία",
    "location": "Μελιταία, Φθιώτιδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.038611",
    "longitude": "22.456995",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100132,
    "nomosId": "magnisia",
    "name": "Παλαιά / Κλασική Άλος",
    "location": "Άλος / Αλμυρός, Μαγνησία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.14763862459458",
    "longitude": "22.82252476265276",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100133,
    "nomosId": "magnisia",
    "name": "Νέα / Ελληνιστική Άλος",
    "location": "Άλος / Αλμυρός, Μαγνησία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.144116",
    "longitude": "22.814496",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100134,
    "nomosId": "voiotia",
    "name": "Αρχαία Αλίαρτος",
    "location": "Αλίαρτος, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.3777778",
    "longitude": "23.0872222",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100135,
    "nomosId": "voiotia",
    "name": "Ιερό Απόλλωνα Δηλίου",
    "location": "Δήλιο / Αυλίδα, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.34249575555569",
    "longitude": "23.67402321246195",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100136,
    "nomosId": "korinthia",
    "name": "Τιτάνη Σικυώνας",
    "location": "Σικυώνα / Τιτάνη, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.92049",
    "longitude": "22.62501",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100137,
    "nomosId": "achaia",
    "name": "Αρχαία Πελλήνη Αχαΐας",
    "location": "Πελλήνη, Αχαΐα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.0444444",
    "longitude": "22.5416667",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100138,
    "nomosId": "korinthia",
    "name": "Αρχαία Νεμέα",
    "location": "Νεμέα, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.80889",
    "longitude": "22.71028",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100139,
    "nomosId": "arkadia",
    "name": "Αρχαία Γόρτυς Αρκαδίας",
    "location": "Γόρτυς Αρκαδίας, Αρκαδία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.539751",
    "longitude": "22.045283",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100140,
    "nomosId": "ileia",
    "name": "Αρχαία Αλίφειρα",
    "location": "Αλίφειρα, Ηλεία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.532",
    "longitude": "21.864",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100141,
    "nomosId": "arkadia",
    "name": "Αρχαία Θεισόα Αρκαδίας",
    "location": "Θεισόα, Αρκαδία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.50667746487136",
    "longitude": "21.96381975812432",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100142,
    "nomosId": "achaia",
    "name": "Αρχαία Ψωφίδα",
    "location": "Ψωφίδα, Αχαΐα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.871694",
    "longitude": "21.892889",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100143,
    "nomosId": "ileia",
    "name": "Αρχαία Φιγαλεία",
    "location": "Φιγαλεία, Ηλεία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.3963",
    "longitude": "21.8391",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100144,
    "nomosId": "argolida",
    "name": "[χωρίς όνομα]",
    "location": "Αργολίδα / άγνωστο pin, Αργολίδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.6570036",
    "longitude": "22.8253274",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100145,
    "nomosId": "aitoloakarnania",
    "name": "Αρχαία Στράτος",
    "location": "Στράτος, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.671667",
    "longitude": "21.319444",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100146,
    "nomosId": "aitoloakarnania",
    "name": "Αρχαίο Θέρμο",
    "location": "Θέρμο, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.55944",
    "longitude": "21.66806",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100147,
    "nomosId": "aitoloakarnania",
    "name": "Αρχαία Καλυδώνα",
    "location": "Καλυδώνα, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.372423",
    "longitude": "21.533106",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100148,
    "nomosId": "aitoloakarnania",
    "name": "Αρχαία Λιμναία",
    "location": "Λιμναία, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.858725",
    "longitude": "21.168321",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100149,
    "nomosId": "aitoloakarnania",
    "name": "Αρχαίο Φραγμα Αλυζειας",
    "location": "Αλυζεία, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.710944",
    "longitude": "20.969972",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100150,
    "nomosId": "aitoloakarnania",
    "name": "[χωρίς όνομα]",
    "location": "Αλυζεία / άγνωστο pin, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.672162",
    "longitude": "21.011468",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100151,
    "nomosId": "aitoloakarnania",
    "name": "[χωρίς όνομα]",
    "location": "Αλυζεία / άγνωστο pin, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.6920423",
    "longitude": "21.0105461",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100152,
    "nomosId": "aitoloakarnania",
    "name": "Ιερό του Ηρακλή Αρχαία Αλυζεία",
    "location": "Αλυζεία, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.677567",
    "longitude": "20.9305274",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100153,
    "nomosId": "aitoloakarnania",
    "name": "Αρχαία Αλυζεία",
    "location": "Αλυζεία, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.69246505969615",
    "longitude": "20.97636041859368",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100154,
    "nomosId": "aitoloakarnania",
    "name": "Αρχαία Χαλκίδα Αιτωλίας",
    "location": "Αρχαία Χαλκίδα Αιτωλίας, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.3537",
    "longitude": "21.6316",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100155,
    "nomosId": "aitoloakarnania",
    "name": "Τείχος Αρχαία Χαλκίδα",
    "location": "Αρχαία Χαλκίδα Αιτωλίας, Αιτωλοακαρνανία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.35026959431314",
    "longitude": "21.61328644402804",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100156,
    "nomosId": "korinthia",
    "name": "Αρχαίες Κλεωνές",
    "location": "Κλεωνές / Νεμέα, Κορινθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.82342380920791",
    "longitude": "22.75238323988558",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100157,
    "nomosId": "kyklades",
    "name": "Ζαγορά Άνδρου",
    "location": "Άνδρος / Ζαγορά, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.774167",
    "longitude": "24.865556",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100158,
    "nomosId": "kyklades",
    "name": "Στρόφιλας Άνδρου",
    "location": "Άνδρος / Στρόφιλας, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.779963",
    "longitude": "24.854888",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100159,
    "nomosId": "lesvos",
    "name": "Κουκονήσι Λήμνου",
    "location": "Κουκονήσι, Λήμνος",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.886",
    "longitude": "25.269",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100160,
    "nomosId": "chios",
    "name": "Εμπορειός Χίου",
    "location": "Εμπορειός, Χίος",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.19389",
    "longitude": "26.02944",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100161,
    "nomosId": "kyklades",
    "name": "Ναός Απόλλωνα στο Δεσποτικό",
    "location": "Δεσποτικό / Αντίπαρος, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.97039",
    "longitude": "25.014307",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100162,
    "nomosId": "voiotia",
    "name": "Αρχαία Ανθηδώνα Βοιωτίας",
    "location": "Ανθηδώνα, Βοιωτία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.498583",
    "longitude": "23.448834",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100163,
    "nomosId": "dodekanisa",
    "name": "Αρχαία Κυμισάλα Ρόδου/ Νεκρόπολη",
    "location": "Ρόδος / Κυμισάλα, Δωδεκάνησα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.1751914",
    "longitude": "27.7595306",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100164,
    "nomosId": "evros",
    "name": "Ιερό των Μεγάλων Θεών Σαμοθράκης",
    "location": "Σαμοθράκη, Έβρος",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.5008",
    "longitude": "25.5301",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100165,
    "nomosId": "kyklades",
    "name": "Παλαιόπολη Άνδρου",
    "location": "Άνδρος / Παλαιόπολη, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.81585441533703",
    "longitude": "24.82642544437502",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100166,
    "nomosId": "kyklades",
    "name": "Ναός Δήμητρας στο Σαγκρί / Γύρουλας Νάξου",
    "location": "Νάξος / Σαγκρί, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.02905946166843",
    "longitude": "25.43130026118545",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100167,
    "nomosId": "kyklades",
    "name": "[χωρίς όνομα]",
    "location": "Νάξος / άγνωστο pin, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.179151",
    "longitude": "25.548185",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100168,
    "nomosId": "kyklades",
    "name": "[χωρίς όνομα]",
    "location": "Νάξος / Φλεριό, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.0834998",
    "longitude": "25.4520812",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100169,
    "nomosId": "kyklades",
    "name": "Κούρος Φλεριού — λατομείο / Φάραγγα",
    "location": "Νάξος / Φλεριό, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.081139",
    "longitude": "25.453944",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100170,
    "nomosId": "kyklades",
    "name": "Σκάρκος Ίου",
    "location": "Ίος / Σκάρκος, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.7318",
    "longitude": "25.2828",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100171,
    "nomosId": "kyklades",
    "name": "Μαρουλάς Κύθνου",
    "location": "Κύθνος / Μαρουλάς, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.44528343458841",
    "longitude": "24.43092165148385",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100172,
    "nomosId": "chalkidiki",
    "name": "Αρχαία Όλυνθος",
    "location": "Όλυνθος, Χαλκιδική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.296",
    "longitude": "23.354",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100173,
    "nomosId": "xanthi",
    "name": "Αρχαία Άβδηρα",
    "location": "Άβδηρα, Ξάνθη",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.933617",
    "longitude": "24.972725",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100174,
    "nomosId": "kavala",
    "name": "Φίλιπποι",
    "location": "Φίλιπποι, Καβάλα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "41.013",
    "longitude": "24.286",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100175,
    "nomosId": "dodekanisa",
    "name": "Βρουλιά Ρόδου",
    "location": "Ρόδος / Βρουλιά, Δωδεκάνησα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.89478643920312",
    "longitude": "27.76503849277816",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100176,
    "nomosId": "dodekanisa",
    "name": "Ακρόπολη Ρόδου",
    "location": "Ρόδος / Ακρόπολη Ρόδου, Δωδεκάνησα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.4402",
    "longitude": "28.20979999999999",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100177,
    "nomosId": "dodekanisa",
    "name": "Ακρόπολη Λίνδου",
    "location": "Ρόδος / Λίνδος, Δωδεκάνησα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.09168106946632",
    "longitude": "28.08813131296852",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100178,
    "nomosId": "dodekanisa",
    "name": "Αρχαία Κάμειρος Ρόδου",
    "location": "Ρόδος / Κάμειρος, Δωδεκάνησα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.33648007355107",
    "longitude": "27.92130934062816",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100179,
    "nomosId": "chalkidiki",
    "name": "Κασσάνδρεια / Αρχαία Ποτίδαια",
    "location": "Ποτίδαια / Κασσάνδρεια, Χαλκιδική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.19656092904811",
    "longitude": "23.33395062025266",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100180,
    "nomosId": "chalkidiki",
    "name": "Αρχαία Στάγειρα",
    "location": "Στάγειρα, Χαλκιδική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.59167",
    "longitude": "23.79472",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100181,
    "nomosId": "chalkidiki",
    "name": "Αρχαία Άκανθος",
    "location": "Άκανθος / Ιερισσός, Χαλκιδική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.38960221390403",
    "longitude": "23.88694442973382",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100182,
    "nomosId": "chalkidiki",
    "name": "Μένδη Χαλκιδικής",
    "location": "Μένδη, Χαλκιδική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.9638889",
    "longitude": "23.4227778",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100183,
    "nomosId": "chalkidiki",
    "name": "Αρχαία Τορώνη",
    "location": "Τορώνη, Χαλκιδική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.97702250614847",
    "longitude": "23.90089503003642",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100184,
    "nomosId": "pieria",
    "name": "Αρχαία Λείβηθρα",
    "location": "Λείβηθρα, Πιερία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.027432",
    "longitude": "22.538824",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100185,
    "nomosId": "imathia",
    "name": "Βασιλικοί Τάφοι Αιγών",
    "location": "Αιγές / Βεργίνα, Ημαθία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.48762791676513",
    "longitude": "22.31965538303877",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100186,
    "nomosId": "pieria",
    "name": "Αρχαία Πύδνα",
    "location": "Πύδνα, Πιερία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.397465",
    "longitude": "22.617359",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100187,
    "nomosId": "kastoria",
    "name": "Νεολιθικός λιμναίος οικισμός Δισπηλιού",
    "location": "Δισπηλιό, Καστοριά",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.4855556",
    "longitude": "21.2919444",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100188,
    "nomosId": "attiki-peiraias",
    "name": "Ιερό Ποσειδώνα Καλαυρείας",
    "location": "Πόρος / Καλαυρεία, Νήσων",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.52261182572519",
    "longitude": "23.48012189787936",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100189,
    "nomosId": "achaia",
    "name": "Αρχαία Αιγείρα",
    "location": "Αιγείρα, Αχαΐα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.12860999999999",
    "longitude": "22.37806",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100190,
    "nomosId": "arkadia",
    "name": "[χωρίς όνομα]",
    "location": "Τεγέα / Μαντίνεια, Αρκαδία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.3931929",
    "longitude": "22.4702981",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100191,
    "nomosId": "attiki-anatoliki",
    "name": "Θέατρο Θορικού",
    "location": "Θορικός / Λαυρεωτική, Ανατολική Αττική",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.73806",
    "longitude": "24.05375",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100192,
    "nomosId": "argolida",
    "name": "Σπήλαιο Φράγχθι",
    "location": "Ερμιονίδα / Φράγχθι, Αργολίδα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.42303206715501",
    "longitude": "23.13102937593052",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100193,
    "nomosId": "trikala",
    "name": "Σπήλαιο Θεόπετρας",
    "location": "Θεόπετρα, Τρίκαλα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.67973644898034",
    "longitude": "21.681145960348",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100194,
    "nomosId": "lakonia",
    "name": "Σπήλαιο Διρού",
    "location": "Μάνη / Διρός, Λακωνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.638",
    "longitude": "22.3807",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100195,
    "nomosId": "evros",
    "name": "Μεσημβρία–Ζώνη",
    "location": "Μεσημβρία-Ζώνη, Έβρος",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.863263",
    "longitude": "25.638093",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100196,
    "nomosId": "samos",
    "name": "Ηραίο Σάμου",
    "location": "Ηραίο Σάμου, Σάμος",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.67194",
    "longitude": "26.88556",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100197,
    "nomosId": "samos",
    "name": "Πυθαγόρειο Σάμου / Αρχαία πόλη Σάμου",
    "location": "Πυθαγόρειο / Σάμος, Σάμος",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.69144981537274",
    "longitude": "26.94100936326083",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100198,
    "nomosId": "attiki-peiraias",
    "name": "Ναός Αφαίας Αίγινας",
    "location": "Αίγινα / Αφαία, Νήσων",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.75416999999999",
    "longitude": "23.53333",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100199,
    "nomosId": "attiki-peiraias",
    "name": "Κολώνα Αίγινας / ναός Απόλλωνα",
    "location": "Αίγινα / Κολώνα, Νήσων",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.750224",
    "longitude": "23.423356",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100200,
    "nomosId": "kyklades",
    "name": "Φυλακωπή Μήλου",
    "location": "Μήλος / Φυλακωπή, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.755",
    "longitude": "24.5046",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100201,
    "nomosId": "kyklades",
    "name": "Μυκηναϊκή Ακρόπολη Σίφνου,",
    "location": "Σίφνος, Κυκλάδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.954172",
    "longitude": "24.721914",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100202,
    "nomosId": "evvoia",
    "name": "Αρχαία Ερέτρια",
    "location": "Ερέτρια, Εύβοια",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.39806",
    "longitude": "23.79056",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100203,
    "nomosId": "evvoia",
    "name": "Ιερό Αρτέμιδος Αμαρυσίας",
    "location": "Αμάρυνθος, Εύβοια",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.38729824701927",
    "longitude": "23.90861714910197",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100204,
    "nomosId": "lakonia",
    "name": "Σπήλαιο / Ιερό Ποσειδώνα / Νεκρομαντείο Ταινάριου",
    "location": "Ταίναρο, Λακωνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.4016667",
    "longitude": "22.4866667",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100205,
    "nomosId": "evvoia",
    "name": "Αρχαία Δύστος Ευβοίας / Πυραμίδα",
    "location": "Δύστος, Εύβοια",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.3552778",
    "longitude": "24.1452778",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100206,
    "nomosId": "evvoia",
    "name": "Λευκαντί / Ξερόπολη Ευβοίας",
    "location": "Λευκαντί, Εύβοια",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "38.40954251363365",
    "longitude": "23.68233092540773",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100207,
    "nomosId": "kavala",
    "name": "Dikili Tash / Ορθόπετρα, Κρηνίδες Καβάλας",
    "location": "Κρηνίδες / Φίλιπποι, Καβάλα",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "41.010278",
    "longitude": "24.308889",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100208,
    "nomosId": "lasithi",
    "name": "Μινωική έπαυλη Αχλαδιών",
    "location": "Αχλάδια, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.1692",
    "longitude": "26.0719",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100209,
    "nomosId": "lasithi",
    "name": "Χαμαίζι",
    "location": "Χαμαίζι, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.1676801805048",
    "longitude": "26.01860985215206",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100210,
    "nomosId": "lasithi",
    "name": "Μύρτος-Πύργος",
    "location": "Μύρτος / Πύργος, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.00694",
    "longitude": "25.59056",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100211,
    "nomosId": "irakleio",
    "name": "Πρινιάς / Ριζηνία",
    "location": "Πρινιάς / Ριζηνία, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.16923018376679",
    "longitude": "25.00634270808808",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100212,
    "nomosId": "irakleio",
    "name": "Μινωικό νεκροταφείο και οικισμός Κούμασα",
    "location": "Κούμασα, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "34.9833",
    "longitude": "25.0131",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100213,
    "nomosId": "lasithi",
    "name": "Πρινιάτικος Πύργος",
    "location": "Πρινιάτικος Πύργος, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.12830599999999",
    "longitude": "25.731389",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100214,
    "nomosId": "irakleio",
    "name": "Μινωικός θολωτός τάφος Καμηλαρίου",
    "location": "Καμηλάρι, Ηράκλειο",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.0453",
    "longitude": "24.7869",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100215,
    "nomosId": "messinia",
    "name": "Ανάκτορο του Νέστορα",
    "location": "Πύλος / Ανάκτορο Νέστορα, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.02714761035205",
    "longitude": "21.69483534264993",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100216,
    "nomosId": "messinia",
    "name": "Θολωτός τάφος IV",
    "location": "Πύλος / Ανάκτορο Νέστορα, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.02845137223919",
    "longitude": "21.6964362733418",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100217,
    "nomosId": "messinia",
    "name": "Θολωτός τάφος ΙΙΙ",
    "location": "Πύλος / Ανάκτορο Νέστορα, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.02313319458891",
    "longitude": "21.68897531948827",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100218,
    "nomosId": "messinia",
    "name": "Μυκηναϊκό νεκροταφείο",
    "location": "Πύλος / Ανάκτορο Νέστορα, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.05814861733096",
    "longitude": "21.72351167142967",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100219,
    "nomosId": "messinia",
    "name": "Θολωτός τάφος 1 / 2",
    "location": "Πύλος / Ανάκτορο Νέστορα, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.03187388709571",
    "longitude": "21.73854178251048",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100220,
    "nomosId": "messinia",
    "name": "Θολωτός τάφος Κορυφασίου",
    "location": "Κορυφάσιο / Πύλος, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.9938348444373",
    "longitude": "21.67850654450441",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100221,
    "nomosId": "messinia",
    "name": "Θολωτός τάφος 1 / 2 στην Τραγάνα",
    "location": "Τραγάνα / Πύλος, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.00074618960632",
    "longitude": "21.66198733253701",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100222,
    "nomosId": "messinia",
    "name": "Αρχαία Ικλαινα",
    "location": "Ίκλαινα, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.9966436",
    "longitude": "21.711105",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100223,
    "nomosId": "messinia",
    "name": "Αρχαϊκό ιερό",
    "location": "Πύλος / Μεσσηνία, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.05277868918204",
    "longitude": "21.7995035962366",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100224,
    "nomosId": "messinia",
    "name": "Θολωτός τάφος",
    "location": "Πύλος / Μεσσηνία, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.96897168973737",
    "longitude": "21.76058148108925",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100225,
    "nomosId": "messinia",
    "name": "Θολωτός τάφος",
    "location": "Πύλος / Μεσσηνία, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.97567311444647",
    "longitude": "21.76105341915551",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100226,
    "nomosId": "messinia",
    "name": "Θολωτός τάφος",
    "location": "Πύλος / Μεσσηνία, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.97724937488712",
    "longitude": "21.75771247479759",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100227,
    "nomosId": "messinia",
    "name": "Ταφικός τύμβος",
    "location": "Πύλος / Μεσσηνία, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "37.01366835165454",
    "longitude": "21.73779852900396",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100228,
    "nomosId": "messinia",
    "name": "Θολωτοί τάφοι Καμινίων",
    "location": "Καμίνια / Πύλος, Μεσσηνία",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "36.98486203313604",
    "longitude": "21.78051039140402",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100229,
    "nomosId": "evros",
    "name": "Η σπηλιά του Πολύφημου",
    "location": "Σπήλαιο Πολύφημου, Έβρος",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.84841903320189",
    "longitude": "25.74666236846402",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100230,
    "nomosId": "magnisia",
    "name": "Σπήλαιο Κύκλωπα Γιούρας",
    "location": "Γιούρα / Σπήλαιο Κύκλωπα, Σποράδες",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "39.38789999999999",
    "longitude": "24.1786",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100231,
    "nomosId": "lasithi",
    "name": "Καβούσι Κάστρο",
    "location": "Καβούσι / Κάστρο, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.111944",
    "longitude": "25.849722",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100232,
    "nomosId": "lasithi",
    "name": "Βρόκαστρο Λασιθίου",
    "location": "Βρόκαστρο, Λασίθι",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "35.1447",
    "longitude": "25.7245",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  },
  {
    "id": 100233,
    "nomosId": "rodopi",
    "name": "Μολυβωτή / Αρχαία Στρύμη",
    "location": "Μολυβωτή / Αρχαία Στρύμη, Ροδόπη",
    "altitude": "",
    "image": "",
    "description": "",
    "latitude": "40.93554918567555",
    "longitude": "25.28764030409486",
    "visited": false,
    "visitDate": "",
    "visitPhoto": ""
  }
];
